apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:5.2.1-apache
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: "mysql1"
        - name: MYSQL_ROOT_PASSWORD
          value: "mydb6789tyui"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 55550
    targetPort: 80
  type: NodePort
