apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql1
spec:
  selector:
    matchLabels:
      app: mysql1
  template:
    metadata:
      labels:
        app: mysql1
    spec:
      containers:
      - name: mysql1
        image: mysql:5.7-debian
        env:
        - name: MYSQL_DATABASE
          value: "mydb_tugas5"
        - name: MYSQL_PASSWORD
          value: "mydb6789tyui"
        - name: MYSQL_ROOT_PASSWORD
          value: "mydb6789tyui"
        - name: MYSQL_ROOT_HOST
          value: "%"
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-storage
        - mountPath: "/docker-entrypoint-initdb.d"
          name: mysql-scripts
      volumes:
      # - name: mysql-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pvc
      - name: mysql-scripts
        hostPath:
          path: /KA-Tugas-5-2024/mysql/dbscripts
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mysql1
spec:
  ports:
    - port: 3306
  selector:
    app: mysql1
  type: ClusterIP
